PHP 8/php-generator v4 compatibility update
uestla/HttpAuthExtension pull request #5
Opened 2023-10-18 15:43 UTC by eydun

PhpGenerator\ClassType.php was refactored in v.4, so $methods-property became private. Fixed by using $class->getMethod('initialize') instead.

2023-10-20 12:49 UTC, uestla requested changes

2023-10-20 12:49 UTC, uestla commented on src/HttpAuthExtension/HttpAuthExtension.php
> +            $initialize = $class->getMethod('initialize');
Please use tabs as the rest of the project.

2023-10-21 17:36 UTC, eydun reviewed
tabs instead of spaces

2023-10-22 19:17 UTC, uestla approved these changes

2023-10-22 19:17 UTC, merged

2023-10-22 19:17 UTC, uestla commented
@eydun Thanks!